"""
CLI for ebdeploy.

Usage:
  ebdeploy init
  ebdeploy init --reconfigure
  ebdeploy deploy
  ebdeploy deploy --version v1.2.3 --dry-run
  ebdeploy status
  ebdeploy package --output deploy.zip
  ebdeploy temp creds
  ebdeploy temp creds --profile myprofile --mfa-serial arn:aws:iam::123:mfa/user
"""

from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

from .config import DeployConfig
from .deployer import Deployer
from .exceptions import DeployError
from .temp_creds import TemporaryCredentialsManager


def _setup_logging(verbose: bool) -> None:
    level = logging.DEBUG if verbose else logging.INFO
    logging.basicConfig(
        level=level,
        format="%(asctime)s [%(levelname)s] %(message)s",
        datefmt="%H:%M:%S",
    )


def _make_deployer(args: argparse.Namespace) -> Deployer:
    cfg = DeployConfig.auto(path=args.config)

    # CLI arguments override config file values
    overrides = {
        "app_name":      getattr(args, "app_name", None),
        "environment":   getattr(args, "environment", None),
        "s3_bucket":     getattr(args, "s3_bucket", None),
        "aws_profile":   getattr(args, "profile", None),
        "aws_region":    getattr(args, "region", None),
    }
    for key, val in overrides.items():
        if val:
            setattr(cfg, key, val)

    return Deployer(cfg)


# ------------------------------------------------------------------ commands

def cmd_init(args: argparse.Namespace) -> int:
    """Interactively create ebdeploy.yml."""
    config_path = Path(args.config)

    if config_path.exists() and not args.reconfigure:
        print(f"Warning: {config_path} already exists.")
        print(f"  To reconfigure, run: ebdeploy init --reconfigure")
        return 1

    config_path.parent.mkdir(parents=True, exist_ok=True)
    action = "Overwriting" if config_path.exists() else "Creating"
    print(f"{action} {config_path}\n")

    project = input("Project name (project): ").strip()
    client  = input("Client name  (client):  ").strip()
    env     = input("Environment  (env):     ").strip()
    bucket  = input("S3 bucket:              ").strip()
    region     = input("AWS region   [us-east-1]: ").strip() or "us-east-1"
    profile    = input("AWS profile  (leave blank to skip): ").strip()
    mfa_serial = input("MFA serial ARN (leave blank to skip): ").strip()

    app_name    = f"{project}-{client}"
    environment = f"{project}-{client}-{env}"
    s3_prefix   = f"{project}/{env}/{client}"

    lines = [
        "# ebdeploy.yml — deployment configuration",
        "# Generated by: ebdeploy init",
        "",
        f"app_name: {app_name}",
        f"environment: {environment}",
        "",
        f"s3_bucket: {bucket}",
        f"s3_prefix: {s3_prefix}",
        "",
        f"aws_region: {region}",
    ]
    if profile:
        lines.append(f"aws_profile: {profile}")
    if mfa_serial:
        lines.append(f"mfa_serial: {mfa_serial}")
    lines += [
        "",
        "archive_path: deploy.zip",
        "use_git_archive: true",
        "",
        "wait_for_ready: true",
        "wait_timeout: 600",
        "poll_interval: 15",
    ]

    config_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"\n✅ Saved: {config_path}")
    print(f"   S3 path: s3://{bucket}/{s3_prefix}/<version>.zip")
    return 0


def cmd_deploy(args: argparse.Namespace) -> int:
    deployer = _make_deployer(args)
    version = deployer.deploy(
        version_label=args.version,
        description=args.description,
        dry_run=args.dry_run,
    )
    print(f"\n✅ Deployed version: {version}")
    return 0


def cmd_status(args: argparse.Namespace) -> int:
    deployer = _make_deployer(args)
    info = deployer.status()
    fields = ["EnvironmentName", "Status", "Health", "VersionLabel", "CNAME"]
    for f in fields:
        if f in info:
            print(f"  {f}: {info[f]}")
    return 0


def cmd_package(args: argparse.Namespace) -> int:
    deployer = _make_deployer(args)
    out = deployer.package(output_path=args.output)
    print(f"✅ Archive: {out}")
    return 0


def cmd_temp_creds(args: argparse.Namespace) -> int:
    """Get temporary AWS credentials via STS + MFA and save to ~/.aws/credentials."""
    profile = getattr(args, 'profile', None)
    mfa_serial = getattr(args, 'mfa_serial', None)

    if not profile or not mfa_serial:
        try:
            cfg = DeployConfig.auto(path=args.config)
            profile = profile or cfg.aws_profile
            mfa_serial = mfa_serial or cfg.mfa_serial
        except Exception:
            pass

    mgr = TemporaryCredentialsManager(profile=profile)

    if not mfa_serial:
        print('Auto-detecting MFA device...')
        mfa_serial = mgr.get_mfa_serial()
        print(f'Found: {mfa_serial}')

    mfa_token = input('Enter MFA token: ').strip()

    creds = mgr.get_temp_credentials(
        mfa_token=mfa_token,
        mfa_serial=mfa_serial,
        duration=args.duration,
    )

    target_profile = f'{profile or "default"}-temp'
    mgr.save_credentials(creds, target_profile)

    print(f'\n✅ Temporary credentials saved as profile: {target_profile}')
    print(f'   Expires: {creds.expiration.strftime("%Y-%m-%d %H:%M:%S UTC")}')
    print(f'\nUsage: ebdeploy deploy --profile {target_profile}')
    return 0


# ------------------------------------------------------------------ main

def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="ebdeploy",
        description="AWS Elastic Beanstalk deployment automation",
    )
    parser.add_argument("-v", "--verbose", action="store_true", help="Verbose output")
    parser.add_argument(
        "-c", "--config", default=".elasticbeanstalk/ebdeploy.yml", metavar="FILE",
        help="Path to config file (default: .elasticbeanstalk/ebdeploy.yml)",
    )

    # Shared AWS arguments
    aws = argparse.ArgumentParser(add_help=False)
    aws.add_argument("--profile", help="AWS profile (~/.aws/credentials)")
    aws.add_argument("--region", help="AWS region")
    aws.add_argument("--app-name", dest="app_name", help="EB application name")
    aws.add_argument("--environment", help="EB environment name")
    aws.add_argument("--s3-bucket", dest="s3_bucket", help="S3 bucket")

    sub = parser.add_subparsers(dest="command", required=True)

    # init
    p_init = sub.add_parser("init", help="Interactively create ebdeploy.yml")
    p_init.add_argument(
        "--reconfigure",
        action="store_true",
        help="Overwrite existing ebdeploy.yml",
    )
    p_init.set_defaults(func=cmd_init)

    # deploy
    p_deploy = sub.add_parser("deploy", parents=[aws], help="Run a deployment")
    p_deploy.add_argument("--version", help="Version label (default: git SHA)")
    p_deploy.add_argument("--description", default="", help="Version description")
    p_deploy.add_argument("--dry-run", action="store_true", help="Build archive without deploying")
    p_deploy.set_defaults(func=cmd_deploy)

    # status
    p_status = sub.add_parser("status", parents=[aws], help="Show EB environment status")
    p_status.set_defaults(func=cmd_status)

    # package
    p_package = sub.add_parser("package", parents=[aws], help="Build archive only")
    p_package.add_argument("--output", default="deploy.zip", help="Output archive path")
    p_package.set_defaults(func=cmd_package)

    # temp
    p_temp = sub.add_parser("temp", help="Temporary credentials management")
    temp_sub = p_temp.add_subparsers(dest="temp_command", required=True)

    # temp creds
    p_temp_creds = temp_sub.add_parser("creds", parents=[aws], help="Get temporary credentials via MFA")
    p_temp_creds.add_argument(
        "--mfa-serial", dest="mfa_serial",
        help="MFA device serial ARN (auto-detected if omitted)",
    )
    p_temp_creds.add_argument(
        "--duration", type=int, default=43200,
        help="Credential lifetime in seconds (default: 43200 = 12h, max: 129600 = 36h)",
    )
    p_temp_creds.set_defaults(func=cmd_temp_creds)

    args = parser.parse_args(argv)
    _setup_logging(args.verbose)

    try:
        return args.func(args)
    except DeployError as e:
        logging.error(str(e))
        return 1
    except KeyboardInterrupt:
        print("\nAborted.")
        return 130


if __name__ == "__main__":
    sys.exit(main())
